feat: icewm, refactor: void tweaks and startup scripts

diff --git a/scripts/.local/bin/ssha b/scripts/.local/bin/ssha
--- a/scripts/.local/bin/ssha
+++ b/scripts/.local/bin/ssha
@@ -1,4 +1,12 @@
 #!/bin/sh
-[ $# -ne 2 ] && echo "Usage: ssha <ssh_key> <pass_path>" && exit 1
 
-PASS_PATH="$2" DISPLAY=1 SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS="$(which ssh_askpass)" ssh-add "$1" < /dev/null
+fatal() {
+    echo "[fatal] $0 : $1"
+    exit 1
+}
+
+[ -z "$1" ] && fatal "Missing key name"
+
+cmd="pass -c ssh/$1 && ssh-add ~/.ssh/$1"
+
+eval $cmd
